import { Movement } from "@shared/schema";

export const polestarPilatesReformerMovements: Partial<Movement>[] = [
  {
    name: "Footwork - Toes",
    category: "Footwork",
    level: "Beginner",
    description: "Working with the toes on the footbar to strengthen feet and ankle stability",
    benefits: ["Improves foot and ankle strength", "Enhances circulation", "Promotes proper alignment"],
    precautions: ["Ankle injuries", "Severe bunions"],
    tags: ["footwork", "beginner", "warm-up"],
    precautionLevel: "low",
  },
  {
    name: "Footwork - Arches",
    category: "Footwork",
    level: "Beginner",
    description: "Placing the arches of the feet on the footbar to work the intrinsic foot muscles",
    benefits: ["Strengthens arch muscles", "Improves foot alignment"],
    precautions: ["Plantar fasciitis", "Severe flat feet"],
    tags: ["footwork", "beginner", "warm-up"],
    precautionLevel: "low",
  },
  {
    name: "Footwork - Heels",
    category: "Footwork",
    level: "Beginner",
    description: "Working with heels on the footbar to target posterior leg muscles",
    benefits: ["Strengthens calves", "Strengthens Achilles tendon", "Improves ankle flexibility"],
    precautions: ["Achilles tendonitis", "Severe ankle instability"],
    tags: ["footwork", "beginner", "warm-up"],
    precautionLevel: "low",
  },
  {
    name: "Hundred",
    category: "Abdominal Work",
    level: "Beginner",
    description: "Classic Pilates exercise performed on the reformer with legs in tabletop or extended",
    benefits: ["Strengthens core", "Improves breath coordination", "Increases endurance"],
    precautions: ["Neck issues", "High blood pressure", "Pregnancy"],
    tags: ["core", "breathing", "warm-up"],
    precautionLevel: "medium",
  },
  {
    name: "Short Box Series - Round Back",
    category: "Spinal Articulation",
    level: "Intermediate",
    description: "Seated on the box, performing spinal flexion with feet under straps",
    benefits: ["Improves spinal flexibility", "Strengthens abdominals", "Enhances body awareness"],
    precautions: ["Acute back pain", "Osteoporosis"],
    tags: ["flexibility", "spine", "core"],
    precautionLevel: "medium",
  },
  {
    name: "Long Stretch",
    category: "Full Body Integration",
    level: "Advanced",
    description: "Plank position on reformer, performing dynamic movement with carriage",
    benefits: ["Full body strengthening", "Core stability", "Shoulder girdle integration"],
    precautions: ["Wrist issues", "Shoulder injuries", "Lower back problems"],
    tags: ["full-body", "advanced", "strength"],
    precautionLevel: "high",
  },
  {
    name: "Eve's Lunge",
    category: "Hip Work",
    level: "Intermediate",
    description: "Lunge position with one foot on platform, other foot on carriage",
    benefits: ["Hip flexor stretch", "Leg alignment", "Balance training"],
    precautions: ["Knee problems", "Hip replacements"],
    tags: ["stretch", "balance", "alignment"],
    precautionLevel: "medium",
  },
  {
    name: "Front Splits",
    category: "Stretches",
    level: "Advanced",
    description: "Split position with front foot on footbar, back foot on carriage",
    benefits: ["Improves flexibility", "Lengthens hamstrings", "Lengthens hip flexors"],
    precautions: ["Hamstring injuries", "Hip issues"],
    tags: ["flexibility", "advanced", "stretch"],
    precautionLevel: "high",
  },
  {
    name: "Knee Stretches",
    category: "Full Body Integration",
    level: "Intermediate",
    description: "Kneeling on carriage, performing various movement patterns",
    benefits: ["Core stability", "Shoulder strength", "Spinal alignment"],
    precautions: ["Knee problems", "Wrist issues"],
    tags: ["core", "alignment", "strength"],
    precautionLevel: "medium",
  },
  {
    name: "Arms - Pulling Straps",
    category: "Arm Work",
    level: "Beginner",
    description: "Supine position, pulling straps with various arm patterns",
    benefits: ["Upper body strength", "Shoulder stability", "Arm coordination"],
    precautions: ["Shoulder injuries", "Neck problems"],
    tags: ["upper-body", "strength", "coordination"],
    precautionLevel: "low",
  }
];

export default polestarPilatesReformerMovements;
